### ISSUE TITLE
[Database] Check if `uniqueidentifier` can be reused within one table.

### ISSUE THREAD

**Issue by sxcore** [BALA-team/Documentation-Share-Shopping#10]
![zrzut ekranu 2018-10-28 16 41 00](https://user-images.githubusercontent.com/13233783/47618194-80937400-dad0-11e8-9ec0-3c6247a48a3a.png)

**Comment by Piateczka** [comment]
Może być użyty
![image](https://user-images.githubusercontent.com/20434182/48569398-dc982e00-e901-11e8-96f7-80e583e177a8.png)
