### ISSUE TITLE
[Database] Check if classes do exchange information

### ISSUE THREAD

**Issue by sxcore** [BALA-team/Documentation-Share-Shopping#9]
![zrzut ekranu 2018-10-28 16 36 54](https://user-images.githubusercontent.com/13233783/47618136-c3a11780-dacf-11e8-83ba-2d29e0bc1526.png)

But according to this image - classed DO exchange some information. Please check.
![zrzut ekranu 2018-10-28 16 38 40](https://user-images.githubusercontent.com/13233783/47618163-0b27a380-dad0-11e8-97ba-a42ea9d3c4ce.png)

**Comment by Drwalcore** [comment]
![zrzut ekranu 2018-10-28 16 36 54](https://user-images.githubusercontent.com/13233783/47618136-c3a11780-dacf-11e8-83ba-2d29e0bc1526.png)

But according to this image - classed DO exchange some information. Please check.
![zrzut ekranu 2018-10-28 16 38 40](https://user-images.githubusercontent.com/13233783/47618163-0b27a380-dad0-11e8-97ba-a42ea9d3c4ce.png)

**Comment by Piateczka** [comment]
done
